# Generated by Django 6.1 on 2026-08-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golongan', models.CharField(help_text='Contoh: III/a, IV/b', max_length=10, unique=True)),
                ('nama_pangkat', models.CharField(help_text='Contoh: Penata Muda, Pembina Utama', max_length=100)),
                ('urutan', models.PositiveIntegerField(default=1, help_text='Untuk pengurutan hirarki pangkat (1=I/a, dst)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'Master Pangkat',
                'ordering': ['urutan'],
            },
        ),
    ]
