# Generated by Django 6.1 on 2026-08-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='agama',
            field=models.CharField(choices=[('ISLAM', 'Islam'), ('KRISTEN', 'Kristen'), ('KATOLIK', 'Katolik'), ('HINDU', 'Hindu'), ('BUDDHA', 'Buddha'), ('KHONGHUCU', 'Khonghucu')], default='ISLAM', max_length=20),
        ),
    ]
