# Generated by Django 6.1 on 2026-08-26 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_pegawai_agama'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='status_keaktifan',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('PENSIUN', 'Pensiun'), ('MUTASI_KELUAR', 'Mutasi Keluar'), ('CLTN', 'Cuti Di Luar Tanggungan Negara'), ('TUGAS_BELAJAR', 'Tugas Belajar')], db_index=True, default='AKTIF', max_length=20),
        ),
        migrations.CreateModel(
            name='RiwayatKepegawaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_transaksi', models.CharField(choices=[('CPNS', 'Pengangkatan CPNS'), ('PNS', 'Pengangkatan PNS'), ('PPPK', 'Pengangkatan PPPK'), ('MUTASI_MASUK', 'Mutasi Masuk'), ('MUTASI_KELUAR', 'Mutasi Keluar'), ('PENSIUN', 'Pensiun'), ('CLTN', 'Cuti Di Luar Tanggungan Negara'), ('TUGAS_BELAJAR', 'Tugas Belajar'), ('REAKTIF', 'Aktif Kembali')], max_length=30)),
                ('tmt', models.DateField(verbose_name='TMT SK')),
                ('nomor_sk', models.CharField(max_length=100)),
                ('tanggal_sk', models.DateField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('file_sk', models.FileField(blank=True, null=True, upload_to='sk_kepegawaian/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kepegawaian', to='pegawai.pegawai')),
            ],
            options={
                'db_table': 'riwayat_kepegawaian',
                'ordering': ['-tmt'],
            },
        ),
    ]
