# Generated by Django 6.1 on 2026-08-26 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0003_pegawai_status_keaktifan_riwayatkepegawaian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='status_keaktifan',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('PENSIUN', 'Pensiun'), ('MUTASI_KELUAR', 'Mutasi Keluar'), ('CLTN', 'Cuti Di Luar Tanggungan Negara'), ('TUGAS_BELAJAR', 'Tugas Belajar'), ('PPPK_PW', 'PPPK Paruh Waktu')], db_index=True, default='AKTIF', max_length=20),
        ),
        migrations.AlterField(
            model_name='riwayatkepegawaian',
            name='jenis_transaksi',
            field=models.CharField(choices=[('CPNS', 'Pengangkatan CPNS'), ('PNS', 'Pengangkatan PNS'), ('PPPK', 'Pengangkatan PPPK'), ('PPPK_PW', 'Pengangkatan PPPK Paruh Waktu'), ('MUTASI_MASUK', 'Mutasi Masuk'), ('MUTASI_KELUAR', 'Mutasi Keluar'), ('PENSIUN', 'Pensiun'), ('CLTN', 'Cuti Di Luar Tanggungan Negara'), ('TUGAS_BELAJAR', 'Tugas Belajar'), ('REAKTIF', 'Aktif Kembali')], max_length=30),
        ),
        migrations.CreateModel(
            name='RiwayatJabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(max_length=200, verbose_name='Nama Jabatan')),
                ('unit_kerja', models.CharField(max_length=200, verbose_name='Unit Kerja / Satuan Kerja')),
                ('jenis_jabatan', models.CharField(choices=[('STRUKTURAL', 'Struktural'), ('FUNGSIONAL', 'Fungsional Umum / Pelaksana'), ('JFT', 'Fungsional Tertentu')], default='FUNGSIONAL', max_length=30)),
                ('tmt_jabatan', models.DateField(verbose_name='TMT Jabatan')),
                ('nomor_sk', models.CharField(max_length=100)),
                ('tanggal_sk', models.DateField()),
                ('pejabat_penetap', models.CharField(blank=True, help_text='Contoh: Bupati / Kepala Dinas', max_length=150, null=True)),
                ('file_sk', models.FileField(blank=True, null=True, upload_to='sk_jabatan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_jabatan', to='pegawai.pegawai')),
            ],
            options={
                'db_table': 'riwayat_jabatan',
                'ordering': ['-tmt_jabatan'],
            },
        ),
    ]
