# Generated by Django 6.1 on 2026-08-26 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jabatan', '0001_initial'),
        ('pegawai', '0004_alter_pegawai_status_keaktifan_and_more'),
        ('unit_kerja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riwayatjabatan',
            name='jenis_jabatan',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatan',
            name='nama_jabatan',
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='jabatan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_pegawai', to='jabatan.jabatan', verbose_name='Jabatan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riwayatjabatan',
            name='file_sk',
            field=models.FileField(blank=True, null=True, upload_to='sk_jabatan/', verbose_name='File SK PDF'),
        ),
        migrations.AlterField(
            model_name='riwayatjabatan',
            name='nomor_sk',
            field=models.CharField(max_length=100, verbose_name='Nomor SK'),
        ),
        migrations.AlterField(
            model_name='riwayatjabatan',
            name='pejabat_penetap',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Pejabat Penetap'),
        ),
        migrations.AlterField(
            model_name='riwayatjabatan',
            name='tanggal_sk',
            field=models.DateField(verbose_name='Tanggal SK'),
        ),
        migrations.AlterField(
            model_name='riwayatjabatan',
            name='unit_kerja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_pegawai', to='unit_kerja.unitkerja', verbose_name='Unit Kerja'),
        ),
    ]
