# Generated by Django 6.1 on 2026-08-26 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangkat', '0001_initial'),
        ('pegawai', '0005_remove_riwayatjabatan_jenis_jabatan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kp', models.CharField(choices=[('REGULER', 'Kenaikan Pangkat Reguler'), ('JABATAN', 'Kenaikan Pangkat Pilihan / Jabatan'), ('PENGABDIAN', 'Kenaikan Pangkat Pengabdian'), ('ANUMERTA', 'Kenaikan Pangkat Anumerta'), ('IJAZAH', 'Penyesuaian Ijazah'), ('AWAL', 'Pengangkatan Awal / CPNS / PPPK')], default='REGULER', max_length=30, verbose_name='Jenis Kenaikan Pangkat')),
                ('tmt_pangkat', models.DateField(verbose_name='TMT Pangkat')),
                ('nomor_sk', models.CharField(max_length=100, verbose_name='Nomor SK')),
                ('tanggal_sk', models.DateField(verbose_name='Tanggal SK')),
                ('pejabat_penetap', models.CharField(blank=True, max_length=150, null=True, verbose_name='Pejabat Penetap')),
                ('file_sk', models.FileField(blank=True, null=True, upload_to='sk_pangkat/', verbose_name='File SK PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pangkat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_pegawai', to='pangkat.pangkat', verbose_name='Pangkat / Golongan')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pangkat', to='pegawai.pegawai')),
            ],
            options={
                'db_table': 'riwayat_pangkat',
                'ordering': ['-tmt_pangkat'],
            },
        ),
    ]
