# Generated by Django 6.1 on 2026-08-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0006_riwayatpangkat'),
        ('pendidikan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=200, verbose_name='Nama Sekolah / Universitas')),
                ('jurusan', models.CharField(blank=True, max_length=150, null=True, verbose_name='Jurusan / Program Studi')),
                ('nomor_ijazah', models.CharField(max_length=100, verbose_name='Nomor Ijazah')),
                ('tanggal_ijazah', models.DateField(verbose_name='Tanggal Ijazah / Lulus')),
                ('tahun_lulus', models.PositiveIntegerField(verbose_name='Tahun Lulus')),
                ('is_pendidikan_pertama', models.BooleanField(default=False, help_text='Centang jika pendidikan ini digunakan saat pengangkatan awal CPNS/PPPK')),
                ('file_ijazah', models.FileField(blank=True, null=True, upload_to='ijazah/', verbose_name='File Ijazah (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pendidikan', to='pegawai.pegawai')),
                ('tingkat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_pegawai', to='pendidikan.tingkatpendidikan', verbose_name='Tingkat / Jenjang Pendidikan')),
            ],
            options={
                'db_table': 'riwayat_pendidikan',
                'ordering': ['-tingkat__urutan', '-tahun_lulus'],
            },
        ),
    ]
