# Generated by Django 6.1 on 2026-08-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0007_riwayatpendidikan'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatjabatan',
            name='status_pelantikan',
            field=models.CharField(choices=[('DILANTIK', 'Definitif / Sudah Dilantik (Jabatan Fungsional/Struktural)'), ('BELUM_DILANTIK', 'CPNS / Tugas Pelaksana (Belum Dilantik JF)')], default='DILANTIK', help_text="Pilih 'CPNS / Tugas Pelaksana' jika CPNS belum diambil sumpah/dilantik ke dalam Jabatan Fungsional.", max_length=20, verbose_name='Status Pelantikan / Pengangkatan'),
        ),
    ]
