# Generated by Django 6.1 on 2026-08-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0008_riwayatjabatan_status_pelantikan'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatpendidikan',
            name='gelar_belakang',
            field=models.CharField(blank=True, help_text='Contoh: S.Kom., M.T., Ph.D.', max_length=100, null=True, verbose_name='Gelar Belakang'),
        ),
        migrations.AddField(
            model_name='riwayatpendidikan',
            name='gelar_depan',
            field=models.CharField(blank=True, help_text='Contoh: Dr., Drs., Ir.', max_length=50, null=True, verbose_name='Gelar Depan'),
        ),
    ]
