# Generated by Django 6.1 on 2026-08-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0009_riwayatpendidikan_gelar_belakang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatpendidikan',
            name='tampilkan_gelar',
            field=models.BooleanField(default=True, help_text='Centang jika gelar dari riwayat pendidikan ini diizinkan untuk dicantumkan di nama pegawai.', verbose_name='Tampilkan Gelar di Nama Resmi'),
        ),
    ]
