# Generated by Django 6.1 on 2026-09-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0010_riwayatpendidikan_tampilkan_gelar'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatkepegawaian',
            name='tmt_selesai',
            field=models.DateField(blank=True, help_text='Diisi khusus untuk PPPK / PPPK Paruh Waktu', null=True, verbose_name='TMT Selesai / Akhir Kontrak'),
        ),
        migrations.AlterField(
            model_name='riwayatkepegawaian',
            name='jenis_transaksi',
            field=models.CharField(choices=[('CPNS', 'Pengangkatan CPNS'), ('PNS', 'Pengangkatan PNS'), ('PPPK', 'Pengangkatan PPPK Awal'), ('PERPANJANGAN_PPPK', 'Perpanjangan Kontrak PPPK'), ('PPPK_PW', 'Pengangkatan PPPK Paruh Waktu'), ('PERPANJANGAN_PPPK_PW', 'Perpanjangan Kontrak PPPK Paruh Waktu'), ('MUTASI_MASUK', 'Mutasi Masuk'), ('MUTASI_KELUAR', 'Mutasi Keluar'), ('PENSIUN', 'Pensiun / Putus Kontrak'), ('CLTN', 'Cuti Di Luar Tanggungan Negara'), ('TUGAS_BELAJAR', 'Tugas Belajar'), ('REAKTIF', 'Aktif Kembali')], max_length=30),
        ),
        migrations.AlterField(
            model_name='riwayatkepegawaian',
            name='nomor_sk',
            field=models.CharField(max_length=100, verbose_name='Nomor SK / Perjanjian Kerja'),
        ),
        migrations.AlterField(
            model_name='riwayatkepegawaian',
            name='tanggal_sk',
            field=models.DateField(verbose_name='Tanggal SK / Perjanjian Kerja'),
        ),
        migrations.AlterField(
            model_name='riwayatkepegawaian',
            name='tmt',
            field=models.DateField(verbose_name='TMT SK / Mulai Kontrak'),
        ),
    ]
