# Generated by Django 6.1 on 2026-08-24 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=150)),
                ('kode', models.CharField(blank=True, help_text='Kode Unit Kerja/Kode SOTK', max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_units', to='unit_kerja.unitkerja', verbose_name='Induk Unit Kerja')),
            ],
            options={
                'verbose_name_plural': 'Master Unit Kerja',
                'ordering': ['nama'],
            },
        ),
    ]
