# Generated by Django 6.1 on 2026-08-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_kerja', '0002_unitkerja_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitkerja',
            name='jenis',
            field=models.CharField(blank=True, choices=[('PEMDA', 'PEMERINTAH DAERAH'), ('DINAS', 'Dinas'), ('BADAN', 'Badan'), ('SETDA', 'Sekretariat Daerah'), ('SEKRETARIAT', 'Sekretariat Dinas/Badan'), ('BAGIAN', 'Bagian'), ('SUBBAG', 'Subbagian'), ('BIDANG', 'Bidang'), ('SUBBID', 'Subbidang'), ('UPTD', 'UPTD / UPT'), ('KECAMATAN', 'Kecamatan'), ('KELURAHAN', 'Kelurahan'), ('LAINNYA', 'Lainnya')], db_index=True, max_length=30, null=True, verbose_name='Jenis Unit Kerja'),
        ),
    ]
