# Generated by Django 6.1 on 2026-08-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TingkatPendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: S1, D3, SMA', max_length=10, unique=True)),
                ('nama', models.CharField(help_text='Contoh: Sarjana (S-1), Diploma III', max_length=50)),
                ('urutan', models.PositiveIntegerField(default=1, help_text='Urutan hirarki pendidikan (1=SD, 7=S3)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'Master Tingkat Pendidikan',
                'ordering': ['urutan'],
            },
        ),
    ]
