# Generated by Django 6.1 on 2026-08-24 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisJabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JenjangJabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('tingkat', models.IntegerField(default=1, help_text='Urutan hirarki jenjang')),
            ],
            options={
                'ordering': ['tingkat'],
            },
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(db_index=True, max_length=150)),
                ('eselon', models.CharField(blank=True, help_text='Khusus Struktural (e.g. II.a, III.a)', max_length=10, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daftar_jabatan', to='jabatan.jenisjabatan')),
                ('jenjang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jabatan.jenjangjabatan')),
            ],
            options={
                'ordering': ['jenis', 'nama_jabatan'],
            },
        ),
    ]
